Verify presence of SENTRY_AUTH_TOKEN in CI

diff --git a/.github/workflows/build-mudlet.yml b/.github/workflows/build-mudlet.yml
--- a/.github/workflows/build-mudlet.yml
+++ b/.github/workflows/build-mudlet.yml
@@ -230,16 +230,18 @@ jobs:
     - name: check ccache stats prior to build
       run: ccache --zero-stats --show-stats
 
-    - name: Check SENTRY_AUTH_TOKEN secret
-      env:
-        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
+    - name: ❌ Fail if SENTRY_AUTH_TOKEN is missing
+          # This step runs only if the secret is missing (empty value)
+      if: ${{ secrets.SENTRY_AUTH_TOKEN == '' }} 
       run: |
-        if [ -z "$SENTRY_AUTH_TOKEN" ]; then
-          echo "❌ SENTRY_AUTH_TOKEN secret is not defined!"
-          exit 1
-        else
-          echo "✅ SENTRY_AUTH_TOKEN secret is defined 🔒"
-        fi
+        echo "::error title=Missing SENTRY_AUTH_TOKEN Secret::The SENTRY_AUTH_TOKEN secret has not been defined in the repository or organization settings."
+        # Causes the job to fail immediately
+        exit 1
+            
+    - name: ✅ Confirm SENTRY_AUTH_TOKEN is present
+      # This step runs only if the secret is defined (non-empty value)
+      if: ${{ secrets.SENTRY_AUTH_TOKEN != '' }}
+      run: echo "The SENTRY_AUTH_TOKEN secret is defined and ready for use. 🔒"
 
     - name: Build Mudlet
       uses: lukka/run-cmake@v3
